directory: /music
library: /config/library.db

import:
  write: yes
  copy: no
  move: yes

paths:
    albumtype:soundtrack: Soundtracks/$album/$track $title

plugins: embedart fetchart parentwork replaygain mbsync musicbrainz edit bpmanalyser

replaygain:
  auto: true
  backend: ffmpeg


bpmanalyser:
  auto: no

edit:
  albumfields: album albumartist genre
  itemfields: track title artist album genre
